// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_cond_t __darwin_pthread_cond_t;
 * }
 */
public final class __darwin_pthread_cond_t extends _opaque_pthread_cond_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private __darwin_pthread_cond_t() {}
}


