// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct __sbuf {
 *     unsigned char* _base;
 *     int _size;
 * };
 * }
 */
public class __sbuf {

    public static MemoryLayout $LAYOUT() {
        return constants$20.const$4;
    }
    public static VarHandle _base$VH() {
        return constants$20.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned char* _base;
     * }
     */
    public static MemorySegment _base$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$20.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned char* _base;
     * }
     */
    public static void _base$set(MemorySegment seg, MemorySegment x) {
        constants$20.const$5.set(seg, x);
    }
    public static MemorySegment _base$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$20.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void _base$set(MemorySegment seg, long index, MemorySegment x) {
        constants$20.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle _size$VH() {
        return constants$21.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int _size;
     * }
     */
    public static int _size$get(MemorySegment seg) {
        return (int)constants$21.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int _size;
     * }
     */
    public static void _size$set(MemorySegment seg, int x) {
        constants$21.const$0.set(seg, x);
    }
    public static int _size$get(MemorySegment seg, long index) {
        return (int)constants$21.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void _size$set(MemorySegment seg, long index, int x) {
        constants$21.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


