// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct accessx_descriptor {
 *     unsigned int ad_name_offset;
 *     int ad_flags;
 *     int ad_pad[2];
 * };
 * }
 */
public class accessx_descriptor {

    public static MemoryLayout $LAYOUT() {
        return constants$54.const$3;
    }
    public static VarHandle ad_name_offset$VH() {
        return constants$54.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int ad_name_offset;
     * }
     */
    public static int ad_name_offset$get(MemorySegment seg) {
        return (int)constants$54.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int ad_name_offset;
     * }
     */
    public static void ad_name_offset$set(MemorySegment seg, int x) {
        constants$54.const$4.set(seg, x);
    }
    public static int ad_name_offset$get(MemorySegment seg, long index) {
        return (int)constants$54.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void ad_name_offset$set(MemorySegment seg, long index, int x) {
        constants$54.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ad_flags$VH() {
        return constants$54.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int ad_flags;
     * }
     */
    public static int ad_flags$get(MemorySegment seg) {
        return (int)constants$54.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int ad_flags;
     * }
     */
    public static void ad_flags$set(MemorySegment seg, int x) {
        constants$54.const$5.set(seg, x);
    }
    public static int ad_flags$get(MemorySegment seg, long index) {
        return (int)constants$54.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void ad_flags$set(MemorySegment seg, long index, int x) {
        constants$54.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment ad_pad$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


