// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * char* (*archive_passphrase_callback)(struct archive*,void* _client_data);
 * }
 */
public interface archive_passphrase_callback {

    java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _client_data);
    static MemorySegment allocate(archive_passphrase_callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$95.const$2, fi, constants$27.const$2, scope);
    }
    static archive_passphrase_callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __client_data) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$95.const$3.invokeExact(symbol, __x0, __client_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


