// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * long (*archive_write_callback)(struct archive*,void* _client_data,void* _buffer,unsigned long _length);
 * }
 */
public interface archive_write_callback {

    long apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _client_data, java.lang.foreign.MemorySegment _buffer, long _length);
    static MemorySegment allocate(archive_write_callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$94.const$0, fi, constants$93.const$5, scope);
    }
    static archive_write_callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __client_data, java.lang.foreign.MemorySegment __buffer, long __length) -> {
            try {
                return (long)constants$94.const$1.invokeExact(symbol, __x0, __client_data, __buffer, __length);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


