// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * long (*archive_read_callback)(struct archive*,void* _client_data,void** _buffer);
 * }
 */
public interface archive_read_callback {

    long apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _client_data, java.lang.foreign.MemorySegment _buffer);
    static MemorySegment allocate(archive_read_callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$92.const$4, fi, constants$39.const$5, scope);
    }
    static archive_read_callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __client_data, java.lang.foreign.MemorySegment __buffer) -> {
            try {
                return (long)constants$92.const$5.invokeExact(symbol, __x0, __client_data, __buffer);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


