// Generated by jextract

package com.github.gotson.nightcompress.panama;

public class archive_h_2 extends archive_h_1 {

    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_GZIP 1
     * }
     */
    public static int ARCHIVE_COMPRESSION_GZIP() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_BZIP2 2
     * }
     */
    public static int ARCHIVE_COMPRESSION_BZIP2() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_COMPRESS 3
     * }
     */
    public static int ARCHIVE_COMPRESSION_COMPRESS() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_PROGRAM 4
     * }
     */
    public static int ARCHIVE_COMPRESSION_PROGRAM() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_LZMA 5
     * }
     */
    public static int ARCHIVE_COMPRESSION_LZMA() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_XZ 6
     * }
     */
    public static int ARCHIVE_COMPRESSION_XZ() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_UU 7
     * }
     */
    public static int ARCHIVE_COMPRESSION_UU() {
        return (int)7L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_RPM 8
     * }
     */
    public static int ARCHIVE_COMPRESSION_RPM() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_LZIP 9
     * }
     */
    public static int ARCHIVE_COMPRESSION_LZIP() {
        return (int)9L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_COMPRESSION_LRZIP 10
     * }
     */
    public static int ARCHIVE_COMPRESSION_LRZIP() {
        return (int)10L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_CPIO_POSIX 65537
     * }
     */
    public static int ARCHIVE_FORMAT_CPIO_POSIX() {
        return (int)65537L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_CPIO_BIN_LE 65538
     * }
     */
    public static int ARCHIVE_FORMAT_CPIO_BIN_LE() {
        return (int)65538L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_CPIO_BIN_BE 65539
     * }
     */
    public static int ARCHIVE_FORMAT_CPIO_BIN_BE() {
        return (int)65539L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_CPIO_SVR4_NOCRC 65540
     * }
     */
    public static int ARCHIVE_FORMAT_CPIO_SVR4_NOCRC() {
        return (int)65540L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_CPIO_SVR4_CRC 65541
     * }
     */
    public static int ARCHIVE_FORMAT_CPIO_SVR4_CRC() {
        return (int)65541L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_CPIO_AFIO_LARGE 65542
     * }
     */
    public static int ARCHIVE_FORMAT_CPIO_AFIO_LARGE() {
        return (int)65542L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_SHAR_BASE 131073
     * }
     */
    public static int ARCHIVE_FORMAT_SHAR_BASE() {
        return (int)131073L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_SHAR_DUMP 131074
     * }
     */
    public static int ARCHIVE_FORMAT_SHAR_DUMP() {
        return (int)131074L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_TAR_USTAR 196609
     * }
     */
    public static int ARCHIVE_FORMAT_TAR_USTAR() {
        return (int)196609L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_TAR_PAX_INTERCHANGE 196610
     * }
     */
    public static int ARCHIVE_FORMAT_TAR_PAX_INTERCHANGE() {
        return (int)196610L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_TAR_PAX_RESTRICTED 196611
     * }
     */
    public static int ARCHIVE_FORMAT_TAR_PAX_RESTRICTED() {
        return (int)196611L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_TAR_GNUTAR 196612
     * }
     */
    public static int ARCHIVE_FORMAT_TAR_GNUTAR() {
        return (int)196612L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_ISO9660_ROCKRIDGE 262145
     * }
     */
    public static int ARCHIVE_FORMAT_ISO9660_ROCKRIDGE() {
        return (int)262145L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_AR_GNU 458753
     * }
     */
    public static int ARCHIVE_FORMAT_AR_GNU() {
        return (int)458753L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_FORMAT_AR_BSD 458754
     * }
     */
    public static int ARCHIVE_FORMAT_AR_BSD() {
        return (int)458754L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READ_FORMAT_CAPS_NONE 0
     * }
     */
    public static int ARCHIVE_READ_FORMAT_CAPS_NONE() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_DATA 1
     * }
     */
    public static int ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_DATA() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_METADATA 2
     * }
     */
    public static int ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_METADATA() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READ_FORMAT_ENCRYPTION_UNSUPPORTED -2
     * }
     */
    public static int ARCHIVE_READ_FORMAT_ENCRYPTION_UNSUPPORTED() {
        return (int)-2L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READ_FORMAT_ENCRYPTION_DONT_KNOW -1
     * }
     */
    public static int ARCHIVE_READ_FORMAT_ENCRYPTION_DONT_KNOW() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_OWNER 1
     * }
     */
    public static int ARCHIVE_EXTRACT_OWNER() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_PERM 2
     * }
     */
    public static int ARCHIVE_EXTRACT_PERM() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_TIME 4
     * }
     */
    public static int ARCHIVE_EXTRACT_TIME() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_NO_OVERWRITE 8
     * }
     */
    public static int ARCHIVE_EXTRACT_NO_OVERWRITE() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_UNLINK 16
     * }
     */
    public static int ARCHIVE_EXTRACT_UNLINK() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_ACL 32
     * }
     */
    public static int ARCHIVE_EXTRACT_ACL() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_FFLAGS 64
     * }
     */
    public static int ARCHIVE_EXTRACT_FFLAGS() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_XATTR 128
     * }
     */
    public static int ARCHIVE_EXTRACT_XATTR() {
        return (int)128L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_SECURE_SYMLINKS 256
     * }
     */
    public static int ARCHIVE_EXTRACT_SECURE_SYMLINKS() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_SECURE_NODOTDOT 512
     * }
     */
    public static int ARCHIVE_EXTRACT_SECURE_NODOTDOT() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_NO_AUTODIR 1024
     * }
     */
    public static int ARCHIVE_EXTRACT_NO_AUTODIR() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_NO_OVERWRITE_NEWER 2048
     * }
     */
    public static int ARCHIVE_EXTRACT_NO_OVERWRITE_NEWER() {
        return (int)2048L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_SPARSE 4096
     * }
     */
    public static int ARCHIVE_EXTRACT_SPARSE() {
        return (int)4096L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_MAC_METADATA 8192
     * }
     */
    public static int ARCHIVE_EXTRACT_MAC_METADATA() {
        return (int)8192L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_NO_HFS_COMPRESSION 16384
     * }
     */
    public static int ARCHIVE_EXTRACT_NO_HFS_COMPRESSION() {
        return (int)16384L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_HFS_COMPRESSION_FORCED 32768
     * }
     */
    public static int ARCHIVE_EXTRACT_HFS_COMPRESSION_FORCED() {
        return (int)32768L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_SECURE_NOABSOLUTEPATHS 65536
     * }
     */
    public static int ARCHIVE_EXTRACT_SECURE_NOABSOLUTEPATHS() {
        return (int)65536L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_CLEAR_NOCHANGE_FFLAGS 131072
     * }
     */
    public static int ARCHIVE_EXTRACT_CLEAR_NOCHANGE_FFLAGS() {
        return (int)131072L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_EXTRACT_SAFE_WRITES 262144
     * }
     */
    public static int ARCHIVE_EXTRACT_SAFE_WRITES() {
        return (int)262144L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READDISK_RESTORE_ATIME 1
     * }
     */
    public static int ARCHIVE_READDISK_RESTORE_ATIME() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READDISK_HONOR_NODUMP 2
     * }
     */
    public static int ARCHIVE_READDISK_HONOR_NODUMP() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READDISK_MAC_COPYFILE 4
     * }
     */
    public static int ARCHIVE_READDISK_MAC_COPYFILE() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READDISK_NO_TRAVERSE_MOUNTS 8
     * }
     */
    public static int ARCHIVE_READDISK_NO_TRAVERSE_MOUNTS() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READDISK_NO_XATTR 16
     * }
     */
    public static int ARCHIVE_READDISK_NO_XATTR() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READDISK_NO_ACL 32
     * }
     */
    public static int ARCHIVE_READDISK_NO_ACL() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_READDISK_NO_FFLAGS 64
     * }
     */
    public static int ARCHIVE_READDISK_NO_FFLAGS() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_MATCH_MTIME 256
     * }
     */
    public static int ARCHIVE_MATCH_MTIME() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_MATCH_CTIME 512
     * }
     */
    public static int ARCHIVE_MATCH_CTIME() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_MATCH_NEWER 1
     * }
     */
    public static int ARCHIVE_MATCH_NEWER() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_MATCH_OLDER 2
     * }
     */
    public static int ARCHIVE_MATCH_OLDER() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_MATCH_EQUAL 16
     * }
     */
    public static int ARCHIVE_MATCH_EQUAL() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_BYTE_ORDER 1234
     * }
     */
    public static int __DARWIN_BYTE_ORDER() {
        return (int)1234L;
    }
    /**
     * {@snippet :
     * #define LITTLE_ENDIAN 1234
     * }
     */
    public static int LITTLE_ENDIAN() {
        return (int)1234L;
    }
    /**
     * {@snippet :
     * #define BIG_ENDIAN 4321
     * }
     */
    public static int BIG_ENDIAN() {
        return (int)4321L;
    }
    /**
     * {@snippet :
     * #define PDP_ENDIAN 3412
     * }
     */
    public static int PDP_ENDIAN() {
        return (int)3412L;
    }
    /**
     * {@snippet :
     * #define BYTE_ORDER 1234
     * }
     */
    public static int BYTE_ORDER() {
        return (int)1234L;
    }
    /**
     * {@snippet :
     * #define NBBY 8
     * }
     */
    public static int NBBY() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define NFDBITS 32
     * }
     */
    public static long NFDBITS() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define AE_IFMT 61440
     * }
     */
    public static short AE_IFMT() {
        return (short)61440L;
    }
    /**
     * {@snippet :
     * #define AE_IFREG 32768
     * }
     */
    public static short AE_IFREG() {
        return (short)32768L;
    }
    /**
     * {@snippet :
     * #define AE_IFLNK 40960
     * }
     */
    public static short AE_IFLNK() {
        return (short)40960L;
    }
    /**
     * {@snippet :
     * #define AE_IFSOCK 49152
     * }
     */
    public static short AE_IFSOCK() {
        return (short)49152L;
    }
    /**
     * {@snippet :
     * #define AE_IFCHR 8192
     * }
     */
    public static short AE_IFCHR() {
        return (short)8192L;
    }
    /**
     * {@snippet :
     * #define AE_IFBLK 24576
     * }
     */
    public static short AE_IFBLK() {
        return (short)24576L;
    }
    /**
     * {@snippet :
     * #define AE_IFDIR 16384
     * }
     */
    public static short AE_IFDIR() {
        return (short)16384L;
    }
    /**
     * {@snippet :
     * #define AE_IFIFO 4096
     * }
     */
    public static short AE_IFIFO() {
        return (short)4096L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_ENTRY_ACL_PERMS_POSIX1E 7
     * }
     */
    public static int ARCHIVE_ENTRY_ACL_PERMS_POSIX1E() {
        return (int)7L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_ENTRY_ACL_PERMS_NFS4 65529
     * }
     */
    public static int ARCHIVE_ENTRY_ACL_PERMS_NFS4() {
        return (int)65529L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_ENTRY_ACL_INHERITANCE_NFS4 2130706432
     * }
     */
    public static int ARCHIVE_ENTRY_ACL_INHERITANCE_NFS4() {
        return (int)2130706432L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_ENTRY_ACL_TYPE_POSIX1E 768
     * }
     */
    public static int ARCHIVE_ENTRY_ACL_TYPE_POSIX1E() {
        return (int)768L;
    }
    /**
     * {@snippet :
     * #define ARCHIVE_ENTRY_ACL_TYPE_NFS4 15360
     * }
     */
    public static int ARCHIVE_ENTRY_ACL_TYPE_NFS4() {
        return (int)15360L;
    }
}


