// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * void (*archive_write_disk_set_group_lookup$x1)(void*);
 * }
 */
public interface archive_write_disk_set_group_lookup$x1 {

    void apply(java.lang.foreign.MemorySegment _x0);
    static MemorySegment allocate(archive_write_disk_set_group_lookup$x1 fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$128.const$1, fi, constants$0.const$3, scope);
    }
    static archive_write_disk_set_group_lookup$x1 ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0) -> {
            try {
                constants$0.const$5.invokeExact(symbol, __x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


