// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * long long (*archive_seek_callback)(struct archive*,void* _client_data,long long offset,int whence);
 * }
 */
public interface archive_seek_callback {

    long apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _client_data, long offset, int whence);
    static MemorySegment allocate(archive_seek_callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$93.const$3, fi, constants$93.const$2, scope);
    }
    static archive_seek_callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __client_data, long _offset, int _whence) -> {
            try {
                return (long)constants$93.const$4.invokeExact(symbol, __x0, __client_data, _offset, _whence);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


