// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * int (*archive_read_disk_set_metadata_filter_callback$_metadata_filter_func)(struct archive*,void*,struct archive_entry*);
 * }
 */
public interface archive_read_disk_set_metadata_filter_callback$_metadata_filter_func {

    int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _client_data1, java.lang.foreign.MemorySegment _client_data2);
    static MemorySegment allocate(archive_read_disk_set_metadata_filter_callback$_metadata_filter_func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$134.const$0, fi, constants$17.const$4, scope);
    }
    static archive_read_disk_set_metadata_filter_callback$_metadata_filter_func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __client_data1, java.lang.foreign.MemorySegment __client_data2) -> {
            try {
                return (int)constants$95.const$1.invokeExact(symbol, __x0, __client_data1, __client_data2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


