// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * int (*archive_close_callback)(struct archive*,void* _client_data);
 * }
 */
public interface archive_close_callback {

    int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _client_data);
    static MemorySegment allocate(archive_close_callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$94.const$4, fi, constants$13.const$0, scope);
    }
    static archive_close_callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __client_data) -> {
            try {
                return (int)constants$94.const$3.invokeExact(symbol, __x0, __client_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


