// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final VarHandle const$0 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_ino"));
    static final VarHandle const$1 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_uid"));
    static final VarHandle const$2 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_gid"));
    static final VarHandle const$3 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_rdev"));
    static final VarHandle const$4 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_size"));
    static final VarHandle const$5 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_blocks"));
}


