// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$139 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$139() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_match_include_pattern_w",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_match_include_pattern_from_file",
        constants$20.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_match_include_pattern_from_file_w",
        constants$20.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_match_path_unmatched_inclusions",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_match_path_unmatched_inclusions_next",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_match_path_unmatched_inclusions_next_w",
        constants$13.const$0
    );
}


