// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vfprintf",
        constants$17.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vprintf",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vsprintf",
        constants$17.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ctermid",
        constants$30.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fdopen",
        constants$34.const$4
    );
}


