// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$164 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$164() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_clear",
        constants$0.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_add_entry",
        constants$164.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_add_entry_w",
        constants$164.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_reset",
        constants$16.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_next",
        constants$164.const$5
    );
}


