// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "putchar_unlocked",
        constants$31.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getw",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "putw",
        constants$12.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tempnam",
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fseeko",
        constants$29.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ftello",
        constants$29.const$3
    );
}


