// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final VarHandle const$0 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_size"));
    static final VarHandle const$1 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_blocks"));
    static final VarHandle const$2 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_blksize"));
    static final VarHandle const$3 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_flags"));
    static final VarHandle const$4 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_gen"));
    static final VarHandle const$5 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_lspare"));
}


