// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$146 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$146() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_fflags",
        constants$112.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_fflags_text",
        constants$30.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_gid",
        constants$29.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_gname",
        constants$30.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_gname_utf8",
        constants$30.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_gname_w",
        constants$30.const$3
    );
}


