// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$79 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$79() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getpeereid",
        constants$17.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getsgroups_np",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getusershell",
        constants$33.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getwgroups_np",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "initgroups",
        constants$16.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "issetugid",
        constants$30.const$1
    );
}


