// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(archive_write_callback.class, "apply", constants$93.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$93.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(archive_open_callback.class, "apply", constants$13.const$0);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(archive_close_callback.class, "apply", constants$13.const$0);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(archive_free_callback.class, "apply", constants$13.const$0);
}


