// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$154 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$154() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_set_devminor",
        constants$68.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_set_filetype",
        constants$68.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_set_fflags",
        constants$113.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_fflags_text",
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_fflags_text_w",
        constants$27.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "archive_entry_set_gid",
        constants$154.const$5
    );
}


