// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$117 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$117() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_compress",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_grzip",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_gzip",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_lrzip",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_lz4",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_lzip",
        constants$18.const$3
    );
}


