// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$71 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$71() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sbrk",
        constants$65.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setpgrp",
        constants$30.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setregid",
        constants$16.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setreuid",
        constants$16.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "swab",
        constants$71.const$4
    );
}


