// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_sourcepath",
        constants$30.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_sourcepath_w",
        constants$30.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_size",
        constants$29.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_size_is_set",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_strmode",
        constants$30.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_symlink",
        constants$30.const$3
    );
}


