// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final VarHandle const$0 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_yday"));
    static final VarHandle const$1 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_isdst"));
    static final VarHandle const$2 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_gmtoff"));
    static final VarHandle const$3 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_zone"));
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("getdate_err", JAVA_INT);
    static final VarHandle const$5 = JAVA_LONG.varHandle();
}


