// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$92 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$92() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_liblzma_version",
        constants$33.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_bzlib_version",
        constants$33.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_liblz4_version",
        constants$33.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_libzstd_version",
        constants$33.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(archive_read_callback.class, "apply", constants$39.const$5);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$39.const$5
    );
}


