// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$69 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$69() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getsid",
        constants$31.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getdtablesize",
        constants$30.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getpagesize",
        constants$30.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getpass",
        constants$30.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getwd",
        constants$30.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "lchown",
        constants$58.const$5
    );
}


