// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$131 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$131() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$61.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(archive_read_disk_set_gname_lookup$x1.class, "apply", constants$0.const$3);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_gname_lookup",
        constants$110.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(archive_read_disk_set_uname_lookup$x0.class, "apply", constants$61.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(archive_read_disk_set_uname_lookup$x1.class, "apply", constants$0.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_uname_lookup",
        constants$110.const$4
    );
}


