// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$149 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$149() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_pathname_utf8",
        constants$30.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_pathname_w",
        constants$30.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_perm",
        constants$145.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_rdev",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_rdevmajor",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_rdevminor",
        constants$18.const$3
    );
}


