// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$111 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$111() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_data_skip",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_data_into_fd",
        constants$16.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_set_format_option",
        constants$110.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_set_filter_option",
        constants$110.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_set_option",
        constants$110.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_set_options",
        constants$13.const$0
    );
}


