// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$42 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$42() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "setlinebuf",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vasprintf",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(funopen$x0.class, "apply", constants$20.const$0);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(funopen$x1.class, "apply", constants$20.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(funopen$x2.class, "apply", constants$23.const$3);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(funopen$x3.class, "apply", constants$18.const$3);
}


