// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final VarHandle const$0 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_mode"));
    static final VarHandle const$1 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_nlink"));
    static final VarHandle const$2 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_ino"));
    static final VarHandle const$3 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_uid"));
    static final VarHandle const$4 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_gid"));
    static final VarHandle const$5 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_rdev"));
}


