// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$87 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$87() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "strtofflags",
        constants$17.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "swapon",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ttyslot",
        constants$30.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "undelete",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "unwhiteout",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "valloc",
        constants$77.const$4
    );
}


