// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$167 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$167() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_xattr_count",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_xattr_reset",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_xattr_next",
        constants$110.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_sparse_clear",
        constants$0.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_sparse_add_entry",
        constants$113.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_sparse_count",
        constants$18.const$3
    );
}


