// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$168 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$168() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_sparse_reset",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_sparse_next",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_linkresolver_new",
        constants$33.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_linkresolver_set_strategy",
        constants$68.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_linkresolver_free",
        constants$0.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_linkify",
        constants$112.const$5
    );
}


