// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fmemopen",
        constants$40.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "open_memstream",
        constants$27.const$2
    );
    static final VarHandle const$3 = JAVA_INT.varHandle();
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("sys_nerr", JAVA_INT);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandleVariadic(
        "asprintf",
        constants$13.const$0
    );
}


