// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final VarHandle const$0 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_file"));
    static final VarHandle const$1 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_lbfsize"));
    static final VarHandle const$2 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_cookie"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(__sFILE._close.class, "apply", constants$18.const$3);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$18.const$3
    );
    static final VarHandle const$5 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_close"));
}


