// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fileno",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "pclose",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "popen",
        constants$27.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__srget",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "__svfscanf",
        constants$17.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "__swbuf",
        constants$12.const$4
    );
}


