// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$134 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$134() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(archive_read_disk_set_metadata_filter_callback$_metadata_filter_func.class, "apply", constants$17.const$4);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_metadata_filter_callback",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_free",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_filter_count",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_filter_bytes",
        constants$63.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_filter_code",
        constants$16.const$0
    );
}


