// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$91 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$91() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sync_volume_np",
        constants$16.const$0
    );
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("optreset", JAVA_INT);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_version_number",
        constants$30.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_version_string",
        constants$33.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_version_details",
        constants$33.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_zlib_version",
        constants$33.const$2
    );
}


