// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$165 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$165() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_to_text_w",
        constants$165.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_to_text",
        constants$165.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_from_text_w",
        constants$20.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_from_text",
        constants$20.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_acl_text_w",
        constants$135.const$0
    );
}


