// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$127 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$127() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_write_set_passphrase",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_write_set_passphrase_callback",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_write_disk_new",
        constants$33.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_write_disk_set_skip_file",
        constants$114.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_write_disk_set_options",
        constants$16.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_write_disk_set_standard_lookup",
        constants$18.const$3
    );
}


