// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$153 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$153() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_set_birthtime",
        constants$113.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_unset_birthtime",
        constants$0.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_set_ctime",
        constants$113.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_unset_ctime",
        constants$0.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_set_dev",
        constants$68.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_set_devmajor",
        constants$68.const$1
    );
}


