// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nfssvc",
        constants$12.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "profil",
        constants$77.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "pthread_setugid_np",
        constants$16.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "pthread_getugid_np",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "reboot",
        constants$31.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "revoke",
        constants$18.const$3
    );
}


