// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "difftime",
        constants$48.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getdate",
        constants$30.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "gmtime",
        constants$30.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "localtime",
        constants$30.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mktime",
        constants$29.const$3
    );
}


