// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$141 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$141() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_match_include_file_time_w",
        constants$57.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_match_exclude_entry",
        constants$57.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_match_owner_excluded",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_match_include_uid",
        constants$72.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_match_include_gid",
        constants$72.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_match_include_uname",
        constants$13.const$0
    );
}


