// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$152 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$152() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_uname_w",
        constants$30.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_is_data_encrypted",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_is_metadata_encrypted",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_is_encrypted",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_set_atime",
        constants$113.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_unset_atime",
        constants$0.const$3
    );
}


