// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$104 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$104() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_zip_streamable",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_zip_seekable",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_set_format",
        constants$16.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_append_filter",
        constants$16.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_append_filter_program",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_append_filter_program_signature",
        constants$97.const$1
    );
}


