// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gethostname",
        constants$72.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "readlink",
        constants$74.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setegid",
        constants$31.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "seteuid",
        constants$31.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "symlink",
        constants$13.const$0
    );
}


