// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$137 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$137() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_copy_error",
        constants$32.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_file_count",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_match_new",
        constants$33.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_match_free",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_match_excluded",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_match_path_excluded",
        constants$13.const$0
    );
}


