// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$140 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$140() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_match_time_excluded",
        constants$13.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_match_include_time",
        constants$140.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_match_include_date",
        constants$57.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_match_include_date_w",
        constants$57.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_match_include_file_time",
        constants$57.const$3
    );
}


