// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$66 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$66() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ttyname_r",
        constants$66.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "unlink",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "write",
        constants$56.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "confstr",
        constants$56.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getopt",
        constants$17.const$0
    );
}


