// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$158 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$158() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_set_mtime",
        constants$113.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_unset_mtime",
        constants$0.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_set_nlink",
        constants$68.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_set_pathname",
        constants$32.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_set_pathname_utf8",
        constants$32.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_pathname",
        constants$32.const$3
    );
}


