// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mkostemp",
        constants$16.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mkostemps",
        constants$58.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mkstemp_dprotected_np",
        constants$58.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mkdtempat_np",
        constants$34.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mkstempsat_np",
        constants$57.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mkostempsat_np",
        constants$56.const$2
    );
}


