// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$143 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$143() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_free",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_new",
        constants$33.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_new2",
        constants$30.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_atime",
        constants$29.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_atime_nsec",
        constants$29.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_atime_is_set",
        constants$18.const$3
    );
}


