// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_support_filter_program",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_support_filter_program_signature",
        constants$97.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_support_filter_rpm",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_support_filter_uu",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_support_filter_xz",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_support_filter_zstd",
        constants$18.const$3
    );
}


