// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getlogin",
        constants$33.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getpgrp",
        constants$30.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getpid",
        constants$30.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getppid",
        constants$30.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getuid",
        constants$30.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "isatty",
        constants$31.const$2
    );
}


