// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rename",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rewind",
        constants$0.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "scanf",
        constants$18.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setbuf",
        constants$32.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "setvbuf",
        constants$32.const$5
    );
}


