// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$116 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$116() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_write_set_compression_program",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_write_set_compression_xz",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter",
        constants$16.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_by_name",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_b64encode",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_bzip2",
        constants$18.const$3
    );
}


