// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sync",
        constants$49.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "truncate",
        constants$72.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ualarm",
        constants$16.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "usleep",
        constants$31.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vfork",
        constants$30.const$1
    );
}


