// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$123 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$123() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_write_zip_set_compression_deflate",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_write_zip_set_compression_store",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_write_open",
        constants$107.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_write_open2",
        constants$107.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_write_open_fd",
        constants$16.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_write_open_filename",
        constants$13.const$0
    );
}


