// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getcwd",
        constants$61.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getegid",
        constants$30.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "geteuid",
        constants$30.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getgid",
        constants$30.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getgroups",
        constants$12.const$4
    );
}


