// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$75 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$75() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(32, JAVA_INT).withName("fds_bits")
    ).withName("fd_set");
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__darwin_check_fd_set_overflow",
        constants$57.const$5
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("tv_sec"),
        JAVA_INT.withName("tv_usec"),
        MemoryLayout.paddingLayout(4)
    ).withName("timeval");
    static final VarHandle const$3 = constants$75.const$2.varHandle(MemoryLayout.PathElement.groupElement("tv_sec"));
    static final VarHandle const$4 = constants$75.const$2.varHandle(MemoryLayout.PathElement.groupElement("tv_usec"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "pselect",
        constants$75.const$5
    );
}


