// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ctermid_r",
        constants$30.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fgetln",
        constants$27.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fmtcheck",
        constants$27.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fpurge",
        constants$18.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "setbuffer",
        constants$41.const$4
    );
}


