// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$68 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$68() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "crypt",
        constants$27.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "encrypt",
        constants$68.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fchdir",
        constants$31.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gethostid",
        constants$47.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getpgid",
        constants$31.const$2
    );
}


