// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$159 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$159() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_pathname_w",
        constants$32.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_update_pathname_utf8",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_set_perm",
        constants$157.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_set_rdev",
        constants$68.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_set_rdevmajor",
        constants$68.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_set_rdevminor",
        constants$68.const$1
    );
}


