// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$95 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$95() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(archive_switch_callback.class, "apply", constants$17.const$4);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(archive_passphrase_callback.class, "apply", constants$27.const$2);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_new",
        constants$33.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_support_compression_all",
        constants$18.const$3
    );
}


