// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$125() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_write_data",
        constants$74.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_write_data_block",
        constants$125.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_write_finish_entry",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_write_close",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_write_fail",
        constants$18.const$3
    );
}


