// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$128 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$128() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(archive_write_disk_set_group_lookup$x0.class, "apply", constants$74.const$1);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(archive_write_disk_set_group_lookup$x1.class, "apply", constants$0.const$3);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_write_disk_set_group_lookup",
        constants$110.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(archive_write_disk_set_user_lookup$x0.class, "apply", constants$74.const$1);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(archive_write_disk_set_user_lookup$x1.class, "apply", constants$0.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_write_disk_set_user_lookup",
        constants$110.const$4
    );
}


