// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$101 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$101() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_7zip",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_all",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_ar",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_by_code",
        constants$16.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_cab",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_cpio",
        constants$18.const$3
    );
}


