// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$105 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$105() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_set_open_callback",
        constants$13.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_set_read_callback",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_set_seek_callback",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_set_skip_callback",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_set_close_callback",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_set_switch_callback",
        constants$13.const$0
    );
}


