// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "strtoumax",
        constants$53.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "wcstoimax",
        constants$53.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "wcstoumax",
        constants$53.const$5
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("ad_name_offset"),
        JAVA_INT.withName("ad_flags"),
        MemoryLayout.sequenceLayout(2, JAVA_INT).withName("ad_pad")
    ).withName("accessx_descriptor");
    static final VarHandle const$4 = constants$54.const$3.varHandle(MemoryLayout.PathElement.groupElement("ad_name_offset"));
    static final VarHandle const$5 = constants$54.const$3.varHandle(MemoryLayout.PathElement.groupElement("ad_flags"));
}


