// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$161 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$161() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_set_symlink_utf8",
        constants$32.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_symlink",
        constants$32.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_symlink_w",
        constants$32.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_update_symlink_utf8",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_set_uid",
        constants$154.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_set_uname",
        constants$32.const$3
    );
}


