// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$110 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$110() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_has_encrypted_entries",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_format_capabilities",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_data",
        constants$74.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_seek_data",
        constants$23.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_data_block",
        constants$110.const$4
    );
}


