// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$138 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$138() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_match_set_inclusion_recursion",
        constants$16.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_match_exclude_pattern",
        constants$13.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_match_exclude_pattern_w",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_match_exclude_pattern_from_file",
        constants$20.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_match_exclude_pattern_from_file_w",
        constants$20.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_match_include_pattern",
        constants$13.const$0
    );
}


