// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$129() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_write_disk_gid",
        constants$74.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_write_disk_uid",
        constants$74.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_disk_new",
        constants$33.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_symlink_logical",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_symlink_physical",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_symlink_hybrid",
        constants$18.const$3
    );
}


