// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$45 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$45() {}
    static final VarHandle const$0 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_min"));
    static final VarHandle const$1 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_hour"));
    static final VarHandle const$2 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_mday"));
    static final VarHandle const$3 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_mon"));
    static final VarHandle const$4 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_year"));
    static final VarHandle const$5 = constants$44.const$4.varHandle(MemoryLayout.PathElement.groupElement("tm_wday"));
}


