// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$93 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$93() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(archive_skip_callback.class, "apply", constants$74.const$1);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$74.const$1
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(archive_seek_callback.class, "apply", constants$93.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$93.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
}


