// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$163 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$163() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_set_is_metadata_encrypted",
        constants$162.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_stat",
        constants$30.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_stat",
        constants$32.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_mac_metadata",
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_copy_mac_metadata",
        constants$71.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_digest",
        constants$135.const$0
    );
}


