// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$65 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$65() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "setuid",
        constants$31.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sleep",
        constants$31.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sysconf",
        constants$52.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tcgetpgrp",
        constants$31.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "tcsetpgrp",
        constants$16.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ttyname",
        constants$65.const$5
    );
}


