// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "tzsetwall",
        constants$49.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "time2posix",
        constants$50.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "timelocal",
        constants$29.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "timegm",
        constants$29.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nanosleep",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "clock_getres",
        constants$12.const$4
    );
}


