// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "pipe",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "read",
        constants$56.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rmdir",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setgid",
        constants$31.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setpgid",
        constants$16.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "setsid",
        constants$30.const$1
    );
}


