// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(__sFILE._read.class, "apply", constants$20.const$0);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$20.const$0
    );
    static final VarHandle const$2 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_read"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(__sFILE._seek.class, "apply", constants$23.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$23.const$3
    );
}


