// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_open_filenames",
        constants$107.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_open_filename_w",
        constants$107.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_open_file",
        constants$107.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_open_memory",
        constants$107.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_open_memory2",
        constants$108.const$4
    );
}


