// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$59 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$59() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "close",
        constants$31.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "dup",
        constants$31.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "dup2",
        constants$16.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandleVariadic(
        "execl",
        constants$13.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "execle",
        constants$13.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandleVariadic(
        "execlp",
        constants$13.const$0
    );
}


