// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "setmode",
        constants$30.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setrgid",
        constants$31.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setruid",
        constants$31.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setsgroups_np",
        constants$12.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setusershell",
        constants$49.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "setwgroups_np",
        constants$12.const$4
    );
}


