// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$80 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$80() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mkdtemp",
        constants$30.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mkpath_np",
        constants$12.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mkpathat_np",
        constants$15.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mkstemp",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mkstemps",
        constants$16.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mktemp",
        constants$30.const$3
    );
}


