// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$133 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$133() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_disk_current_filesystem_is_remote",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_atime_restored",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_behavior",
        constants$16.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(archive_read_disk_set_matching$_excluded_func.class, "apply", constants$112.const$5);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$112.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_matching",
        constants$110.const$4
    );
}


