// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getc",
        constants$18.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getchar",
        constants$30.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gets",
        constants$30.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "perror",
        constants$0.const$3
    );
}


