// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final VarHandle const$0 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_seek"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(__sFILE._write.class, "apply", constants$20.const$0);
    static final VarHandle const$2 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_write"));
    static final VarHandle const$3 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_extra"));
    static final VarHandle const$4 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_ur"));
    static final VarHandle const$5 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("_blksize"));
}


