// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$119 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$119() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_write_add_filter_zstd",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_write_set_format",
        constants$16.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_write_set_format_by_name",
        constants$13.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_write_set_format_7zip",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_write_set_format_ar_bsd",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_write_set_format_ar_svr4",
        constants$18.const$3
    );
}


