// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_uid"));
    static final VarHandle const$1 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_gid"));
    static final VarHandle const$2 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_rdev"));
    static final VarHandle const$3 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_size"));
    static final VarHandle const$4 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_blksize"));
    static final VarHandle const$5 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_blocks"));
}


