// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getdomainname",
        constants$16.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getgrouplist",
        constants$78.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "gethostuuid",
        constants$13.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_SHORT,
        RuntimeHelper.POINTER,
        JAVA_SHORT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getmode",
        constants$78.const$4
    );
}


