// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final VarHandle const$0 = constants$4.const$4.varHandle(MemoryLayout.PathElement.groupElement("tv_nsec"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("st_dev"),
        MemoryLayout.paddingLayout(6),
        JAVA_LONG.withName("st_ino"),
        JAVA_SHORT.withName("st_mode"),
        JAVA_SHORT.withName("st_nlink"),
        JAVA_SHORT.withName("st_uid"),
        JAVA_SHORT.withName("st_gid"),
        JAVA_SHORT.withName("st_rdev"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("st_size"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_atimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_mtimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_ctimespec"),
        JAVA_INT.withName("st_blksize"),
        JAVA_INT.withName("st_blocks"),
        JAVA_INT.withName("st_flags"),
        JAVA_INT.withName("st_gen")
    ).withName("ostat");
    static final VarHandle const$2 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_dev"));
    static final VarHandle const$3 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_ino"));
    static final VarHandle const$4 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_mode"));
    static final VarHandle const$5 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("st_nlink"));
}


