// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final VarHandle const$0 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_blksize"));
    static final VarHandle const$1 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_flags"));
    static final VarHandle const$2 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_gen"));
    static final VarHandle const$3 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("st_lspare"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("st_dev"),
        JAVA_SHORT.withName("st_mode"),
        JAVA_SHORT.withName("st_nlink"),
        JAVA_LONG.withName("st_ino"),
        JAVA_INT.withName("st_uid"),
        JAVA_INT.withName("st_gid"),
        JAVA_INT.withName("st_rdev"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_atimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_mtimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_ctimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_birthtimespec"),
        JAVA_LONG.withName("st_size"),
        JAVA_LONG.withName("st_blocks"),
        JAVA_INT.withName("st_blksize"),
        JAVA_INT.withName("st_flags"),
        JAVA_INT.withName("st_gen"),
        JAVA_INT.withName("st_lspare"),
        MemoryLayout.sequenceLayout(2, JAVA_LONG).withName("st_qspare")
    ).withName("stat64");
    static final VarHandle const$5 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("st_dev"));
}


