// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$130 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$130() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_disk_entry_from_file",
        constants$130.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_disk_gname",
        constants$61.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_disk_uname",
        constants$61.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_disk_set_standard_lookup",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(archive_read_disk_set_gname_lookup$x0.class, "apply", constants$61.const$0);
}


