// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "asctime_r",
        constants$27.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ctime_r",
        constants$27.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gmtime_r",
        constants$27.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "localtime_r",
        constants$27.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "posix2time",
        constants$50.const$4
    );
}


