// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$136 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$136() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_errno",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_error_string",
        constants$30.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_format_name",
        constants$30.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_format",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_clear_error",
        constants$0.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandleVariadic(
        "archive_set_error",
        constants$136.const$5
    );
}


