// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$102 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$102() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_empty",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_gnutar",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_iso9660",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_lha",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_mtree",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_read_support_format_rar",
        constants$18.const$3
    );
}


