// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$135 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$135() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_filter_name",
        constants$135.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_position_compressed",
        constants$29.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_position_uncompressed",
        constants$29.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_compression_name",
        constants$30.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_compression",
        constants$18.const$3
    );
}


