// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$145 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$145() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_dev",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_dev_is_set",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_devmajor",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_devminor",
        constants$18.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_SHORT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_filetype",
        constants$145.const$4
    );
}


