// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;

final class constants$148 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$148() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "archive_entry_mode",
        constants$145.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "archive_entry_mtime",
        constants$29.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "archive_entry_mtime_nsec",
        constants$29.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "archive_entry_mtime_is_set",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "archive_entry_nlink",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "archive_entry_pathname",
        constants$30.const$3
    );
}


