// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$88 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$88() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "syscall",
        constants$31.const$2
    );
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("suboptarg", RuntimeHelper.POINTER);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getsubopt",
        constants$17.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fgetattrlist",
        constants$88.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fsetattrlist",
        constants$88.const$3
    );
}


