// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct __sFILE FILE;
 * }
 */
public final class FILE extends __sFILE {

    // Suppresses default constructor, ensuring non-instantiability.
    private FILE() {}
}


