// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.foreign.*;

/**
 * {@snippet :
 * int (*funopen$x3)(void*);
 * }
 */
public interface funopen$x3 {

    int apply(java.lang.foreign.MemorySegment _x0);
    static MemorySegment allocate(funopen$x3 fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$42.const$5, fi, constants$18.const$3, scope);
    }
    static funopen$x3 ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0) -> {
            try {
                return (int)constants$22.const$4.invokeExact(symbol, __x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


