// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_rwlock_t pthread_rwlock_t;
 * }
 */
public final class pthread_rwlock_t extends _opaque_pthread_rwlock_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_rwlock_t() {}
}


