// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_mutex_t pthread_mutex_t;
 * }
 */
public final class pthread_mutex_t extends _opaque_pthread_mutex_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_mutex_t() {}
}


