// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_condattr_t pthread_condattr_t;
 * }
 */
public final class pthread_condattr_t extends _opaque_pthread_condattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_condattr_t() {}
}


