// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_rwlockattr_t pthread_rwlockattr_t;
 * }
 */
public final class pthread_rwlockattr_t extends _opaque_pthread_rwlockattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_rwlockattr_t() {}
}


