// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_cond_t pthread_cond_t;
 * }
 */
public final class pthread_cond_t extends _opaque_pthread_cond_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_cond_t() {}
}


