// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_once_t pthread_once_t;
 * }
 */
public final class pthread_once_t extends _opaque_pthread_once_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_once_t() {}
}


