// Generated by jextract

package com.github.gotson.nightcompress.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_mutexattr_t pthread_mutexattr_t;
 * }
 */
public final class pthread_mutexattr_t extends _opaque_pthread_mutexattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_mutexattr_t() {}
}


