// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct timespec {
 *     __darwin_time_t tv_sec;
 *     long tv_nsec;
 * };
 * }
 */
public class timespec {

    public static MemoryLayout $LAYOUT() {
        return constants$4.const$4;
    }
    public static VarHandle tv_sec$VH() {
        return constants$4.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __darwin_time_t tv_sec;
     * }
     */
    public static long tv_sec$get(MemorySegment seg) {
        return (long)constants$4.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __darwin_time_t tv_sec;
     * }
     */
    public static void tv_sec$set(MemorySegment seg, long x) {
        constants$4.const$5.set(seg, x);
    }
    public static long tv_sec$get(MemorySegment seg, long index) {
        return (long)constants$4.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void tv_sec$set(MemorySegment seg, long index, long x) {
        constants$4.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle tv_nsec$VH() {
        return constants$5.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long tv_nsec;
     * }
     */
    public static long tv_nsec$get(MemorySegment seg) {
        return (long)constants$5.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long tv_nsec;
     * }
     */
    public static void tv_nsec$set(MemorySegment seg, long x) {
        constants$5.const$0.set(seg, x);
    }
    public static long tv_nsec$get(MemorySegment seg, long index) {
        return (long)constants$5.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void tv_nsec$set(MemorySegment seg, long index, long x) {
        constants$5.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


