// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct timeval {
 *     __darwin_time_t tv_sec;
 *     __darwin_suseconds_t tv_usec;
 * };
 * }
 */
public class timeval {

    public static MemoryLayout $LAYOUT() {
        return constants$75.const$2;
    }
    public static VarHandle tv_sec$VH() {
        return constants$75.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __darwin_time_t tv_sec;
     * }
     */
    public static long tv_sec$get(MemorySegment seg) {
        return (long)constants$75.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __darwin_time_t tv_sec;
     * }
     */
    public static void tv_sec$set(MemorySegment seg, long x) {
        constants$75.const$3.set(seg, x);
    }
    public static long tv_sec$get(MemorySegment seg, long index) {
        return (long)constants$75.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void tv_sec$set(MemorySegment seg, long index, long x) {
        constants$75.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle tv_usec$VH() {
        return constants$75.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __darwin_suseconds_t tv_usec;
     * }
     */
    public static int tv_usec$get(MemorySegment seg) {
        return (int)constants$75.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __darwin_suseconds_t tv_usec;
     * }
     */
    public static void tv_usec$set(MemorySegment seg, int x) {
        constants$75.const$4.set(seg, x);
    }
    public static int tv_usec$get(MemorySegment seg, long index) {
        return (int)constants$75.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void tv_usec$set(MemorySegment seg, long index, int x) {
        constants$75.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


