// Generated by jextract

package com.github.gotson.nightcompress.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct accessx_descriptor {
 *     unsigned int ad_name_offset;
 *     int ad_flags;
 *     int ad_pad[2];
 * }
 * }
 */
public class accessx_descriptor {

    accessx_descriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        archive_h.C_INT.withName("ad_name_offset"),
        archive_h.C_INT.withName("ad_flags"),
        MemoryLayout.sequenceLayout(2, archive_h.C_INT).withName("ad_pad")
    ).withName("accessx_descriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ad_name_offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ad_name_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int ad_name_offset
     * }
     */
    public static final OfInt ad_name_offset$layout() {
        return ad_name_offset$LAYOUT;
    }

    private static final long ad_name_offset$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int ad_name_offset
     * }
     */
    public static final long ad_name_offset$offset() {
        return ad_name_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int ad_name_offset
     * }
     */
    public static int ad_name_offset(MemorySegment struct) {
        return struct.get(ad_name_offset$LAYOUT, ad_name_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int ad_name_offset
     * }
     */
    public static void ad_name_offset(MemorySegment struct, int fieldValue) {
        struct.set(ad_name_offset$LAYOUT, ad_name_offset$OFFSET, fieldValue);
    }

    private static final OfInt ad_flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ad_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ad_flags
     * }
     */
    public static final OfInt ad_flags$layout() {
        return ad_flags$LAYOUT;
    }

    private static final long ad_flags$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ad_flags
     * }
     */
    public static final long ad_flags$offset() {
        return ad_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ad_flags
     * }
     */
    public static int ad_flags(MemorySegment struct) {
        return struct.get(ad_flags$LAYOUT, ad_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ad_flags
     * }
     */
    public static void ad_flags(MemorySegment struct, int fieldValue) {
        struct.set(ad_flags$LAYOUT, ad_flags$OFFSET, fieldValue);
    }

    private static final SequenceLayout ad_pad$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ad_pad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ad_pad[2]
     * }
     */
    public static final SequenceLayout ad_pad$layout() {
        return ad_pad$LAYOUT;
    }

    private static final long ad_pad$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ad_pad[2]
     * }
     */
    public static final long ad_pad$offset() {
        return ad_pad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ad_pad[2]
     * }
     */
    public static MemorySegment ad_pad(MemorySegment struct) {
        return struct.asSlice(ad_pad$OFFSET, ad_pad$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ad_pad[2]
     * }
     */
    public static void ad_pad(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ad_pad$OFFSET, ad_pad$LAYOUT.byteSize());
    }

    private static long[] ad_pad$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int ad_pad[2]
     * }
     */
    public static long[] ad_pad$dimensions() {
        return ad_pad$DIMS;
    }
    private static final VarHandle ad_pad$ELEM_HANDLE = ad_pad$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int ad_pad[2]
     * }
     */
    public static int ad_pad(MemorySegment struct, long index0) {
        return (int)ad_pad$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int ad_pad[2]
     * }
     */
    public static void ad_pad(MemorySegment struct, long index0, int fieldValue) {
        ad_pad$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

